### ISSUE TITLE
ITM Landscape 

### ISSUE THREAD

**Issue by lajidey-foss** [phamos-eu/it_management#262]
Create (or rename) ITM IT Landscape and ITM Host Item make sure that "ITM Host Item" has a link to ITM IT Landscape and that both Doctypes are linked on the Workspace....

### Status:
There is a Doctype IT Landscape that needs to be renamed following the newly introduced naming rules for the overall app. IT Landscape shall be changed to ITM IT Landscape

### Todo:
- [x] Discuss if "old" Doctype can be removed or shall stay
- [x] Create new Doctype ITM IT Landscape
- [x] make sure that links to and from this doctype are checked
- [x] sign of with project manager
- [x] [create PR](https://github.com/phamos-eu/it_management/pull/263) https://github.com/phamos-eu/it_management/pull/263
