### ISSUE TITLE
Assets Address 

### ISSUE THREAD

**Issue by lajidey-foss** [phamos-eu/it_management#264]
In dealing with solutions, interestingly we want to know how to access various assets both tangible and non tangible assets, it could be in any form of address indicator.
### Status:
To achieve this, a doctype needs to be created that can reflect various assets address.

### Todo:
- [ ] Create a doctype name it ITM Location
- [ ] Make sure the doctype a tree
- [ ] Sign off with project manager
- [ ] Create PR

**Comment by wojosc** [comment]
In the Doctype ITM Location we will wan't a link field to an address. As the ITM Location can only be at one address, we will only need a link field and no option to add several addresses. But we will want to use standard functionality of address seen in other frappe/ERPNExt process

In the ITM Location Doctype we need a field `location_address`
![image](https://github.com/phamos-eu/it_management/assets/22279621/7f66e7ac-2f3f-4981-add6-b035a56aa125)

When the user fills this field and a html field below the address should be updated showing the content of the address similar to what can be seen in the customer doctype (here in green)
![image](https://github.com/phamos-eu/it_management/assets/22279621/39212a22-266e-49e9-a24c-e27f2c1b97b4)

As we do not need several addresses the button seen in the image in red is not necessary.

Then, when saving ITM Location we will wan't to update the link in the table of Address Doctype
![image](https://github.com/phamos-eu/it_management/assets/22279621/5b6c4efc-baeb-4848-968a-49aac5cad11c)
