### ISSUE TITLE
Software assets Tracking 

### ISSUE THREAD

**Issue by lajidey-foss** [phamos-eu/it_management#270]
With IT Management both hardware and software assets can be monitored and tracked,as both are uniquely different in terms of what needs to be tracked and also in form factor we might need to track both separately, for this we'll focus our attention on the software assets.
This Doctype will represent software in general. It will be a database for tracking what software products are used within a Landscape (ITM Landscape).
This can be operating Systems, Client Software like Thunderbird, Server Software like Microsoft Exchange or eben Firmware like something that is installed to a router. 
This doctype Instance represents an actual installation of a Software that we are tracking in a database on a Host Item, example will be installing Linux Ubuntu to a Laptop.

### Todo:
- [ ] Discuss the proper name for doctype 
- [ ] Create new Doctype 
- [ ] sign of with project manager
- [ ] Create docfields and links to ITM Host Item Doctype 
- [ ] [create PR]
